name: CI

on: [push]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [macos-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: atom --test spec
